exclusions:
    - { name: OroCRM\Bundle\MagentoBundle\OroCRMMagentoBundle }
    - { name: OroCRM\Bundle\DemoDataBundle\OroCRMDemoDataBundle }
    - { name: OroCRM\Bundle\MagentoContactUsBundle\OroCRMMagentoContactUsBundle }